services:
  postgres:
    image: postgres:15
    container_name: postgres-drivenpass
    ports:
      - 5433:5432
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - pg-drivenpass:/var/lib/postgresql/data
  node_app:
    container_name: backend-drivenpass
    build: .
    ports:
      - 5000:3000
    networks:
      - my-network
    env_file:
      - .env
    depends_on:
      - postgres

networks:
      my-network:
        name: my-network
        driver: bridge
volumes:
  pg-drivenpass: